/**:
  ros__parameters:
    use_legacy_cmd: fasle
    # Arduino 시리얼 포트 설정
    port: /dev/ttyACM0
    baudrate: 115200

    # 차량 파라미터
    max_speed_mps: 2.0
    max_steer_deg: 30.0
    center_servo_deg: 90.0
